name: Build and Release APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # --- NOVO: RESTAURA A KEYSTORE OFICIAL DOS SECRETS ---
      - name: Restaurar Keystore de Produção
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/app/keystore-producao.jks

      # --- ALTERADO: COMPILA A VERSÃO RELEASE USANDO A SUA CHAVE ---
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/app/keystore-producao.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # --- ALTERADO: O CAMINHO AGORA APONTA PARA A PASTA RELEASE ---
      - name: Renomear APK para MotApp
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MotApp.apk

      - name: MotApp Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: MotApp Versão v1.0.${{ github.run_number }}
          body: "Nova atualização automática do MotApp assinada com chave oficial e correções recentes."
          files: app/build/outputs/apk/release/MotApp.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
